#
#This will update and install only the security updates
#
---
- hosts: all
  become: yes

  tasks:
  - name: Обновление пакетов безопасности и микрокода ядра 
    shell: unattended-upgrade --dry-run -d

  - name: удаление старых ядер 
    shell: apt-get autoremove

  - name: удаление старых версий пакетов
    shell: apt-get autoclean
